version: 2
jobs:
  build:
    docker:
      - image: golang:1.8

    working_directory: /go/src/github.com/mlabouardy/swaggymnia

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: go get -v

      - run:
          name: Run Unit Tests
          command: go test

      - setup_remote_docker

      - run:
          name: Install Docker Client
          command: |
            set -x
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$DOCKER_VERSION.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run:
          name: Build Docker image
          command: docker build -t mlabouardy/swaggymnia:$CIRCLE_SHA1 .

      - run:
          name: Push to DockerHub
          command: |
            docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
            docker push mlabouardy/swaggymnia:$CIRCLE_SHA1
